prog: num_generator.c selection_sort.c insertion_sort.c main.c radix_sort.c shell_sort.c
    gcc num_generator.c -o num_generator;
    gcc selection_sort.c -o selection_sort;
    gcc insertion_sort.c -o insertion_sort;
    gcc radix_sort.c -o radix_sort;
    gcc main.c -0 main;
    gcc shell_sort.c -o shell_sort;